entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  postgres:
    address: :5432
  metrics:
    address: :8080

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: ${SERVER_OWNER_EMAIL:-admin@example.com}
      storage: '/letsencrypt/acme.json'
      tlsChallenge: {}

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics